name: CryptoCurrency
version: ${project.version}
main: com.rabbitcompany.CryptoCurrency
api-version: 1.13
softdepend: [ Vault, PlaceholderAPI ]
authors: [ Black1_TV ]
description: Unleash the Crypto Revolution in Minecraft!
website: https://rabbit-company.com